import i18n, { browserLanguage } from '@/locales/i18n'
import { defineStore } from 'pinia'
import { defaultImageList, defaultMusicList, defaultPatternList } from './data'

export const useGlobalConfig = defineStore('global', {
  state() {
    return {
      globalConfig: {
        rowCount: 17,
        isSHowPrizeList: true,
        isShowAvatar: false,
        topTitle: i18n.global.t('data.defaultTitle'),
        language: browserLanguage,
        positionMode: true,
        theme: {
          name: 'dracula',
          detail: { primary: '#0f5fd3' },
          cardColor: '#ff79c6',
          cardWidth: 140,
          cardHeight: 200,
          textColor: '#ffffff',
          luckyCardColor: '#ECB1AC',
          textSize: 30,
          patternColor: '#1b66c9',
          patternList: defaultPatternList,
          background: {},
        },
        musicList: defaultMusicList,
        imageList: defaultImageList,
      },
      currentMusic: { item: defaultMusicList[0], paused: true },
    }
  },
  getters: {
    getGlobalConfig(state) { return state.globalConfig },
    getTopTitle(state) { return state.globalConfig.topTitle },
    getRowCount(state) { return state.globalConfig.rowCount },
    getTheme(state) { return state.globalConfig.theme },
    getCardColor(state) { return state.globalConfig.theme.cardColor },
    getLuckyColor(state) { return state.globalConfig.theme.luckyCardColor },
    getTextColor(state) { return state.globalConfig.theme.textColor },
    getCardSize(state) { return { width: state.globalConfig.theme.cardWidth, height: state.globalConfig.theme.cardHeight } },
    getTextSize(state) { return state.globalConfig.theme.textSize },
    getPatterColor(state) { return state.globalConfig.theme.patternColor },
    getPatternList(state) { return state.globalConfig.theme.patternList },
    getMusicList(state) { return state.globalConfig.musicList },
    getCurrentMusic(state) { return state.currentMusic },
    getImageList(state) { return state.globalConfig.imageList },
    getIsShowPrizeList(state) { return state.globalConfig.isSHowPrizeList },
    getLanguage(state) { return state.globalConfig.language },
    getBackground(state) { return state.globalConfig.theme.background },
    getIsShowAvatar(state) { return state.globalConfig.isShowAvatar },
    getPositionMode(state) { return state.globalConfig.positionMode },
  },
  actions: {
    setRowCount(rowCount) { this.globalConfig.rowCount = rowCount },
    setTopTitle(topTitle) { this.globalConfig.topTitle = topTitle },
    setTheme(theme) { const { name, detail } = theme; this.globalConfig.theme.name = name; this.globalConfig.theme.detail = detail },
    setCardColor(cardColor) { this.globalConfig.theme.cardColor = cardColor },
    setLuckyCardColor(luckyCardColor) { this.globalConfig.theme.luckyCardColor = luckyCardColor },
    setTextColor(textColor) { this.globalConfig.theme.textColor = textColor },
    setCardSize(cardSize) { this.globalConfig.theme.cardWidth = cardSize.width; this.globalConfig.theme.cardHeight = cardSize.height },
    setTextSize(textSize) { this.globalConfig.theme.textSize = textSize },
    setPatterColor(patterColor) { this.globalConfig.theme.patternColor = patterColor },
    setPatternList(patternList) { this.globalConfig.theme.patternList = patternList },
    resetPatternList() { this.globalConfig.theme.patternList = defaultPatternList },
    addMusic(music) { if (this.globalConfig.musicList.some(m => m.name === music.name)) return; this.globalConfig.musicList.push(music) },
    removeMusic(musicId) { const i = this.globalConfig.musicList.findIndex(m => m.id === musicId); if (i >= 0) this.globalConfig.musicList.splice(i, 1) },
    setCurrentMusic(musicItem, paused = true) { this.currentMusic = { item: musicItem, paused } },
    resetMusicList() { this.globalConfig.musicList = JSON.parse(JSON.stringify(defaultMusicList)) },
    clearMusicList() { this.globalConfig.musicList = [] },
    addImage(image) { if (this.globalConfig.imageList.some(img => img.name === image.name)) return; this.globalConfig.imageList.push(image) },
    removeImage(imageId) { const i = this.globalConfig.imageList.findIndex(img => img.id === imageId); if (i >= 0) this.globalConfig.imageList.splice(i, 1) },
    resetImageList() { this.globalConfig.imageList = defaultImageList },
    clearImageList() { this.globalConfig.imageList = [] },
    setIsShowPrizeList(isShowPrizeList) { this.globalConfig.isSHowPrizeList = isShowPrizeList },
    setLanguage(language) { this.globalConfig.language = language; i18n.global.locale.value = language },
    setBackground(background) { this.globalConfig.theme.background = background },
    setIsShowAvatar(isShowAvatar) { this.globalConfig.isShowAvatar = isShowAvatar },
    setPositionMode(mode) { this.globalConfig.positionMode = mode },
    reset() {
      this.globalConfig = {
        rowCount: 17,
        isSHowPrizeList: true,
        isShowAvatar: false,
        topTitle: i18n.global.t('data.defaultTitle'),
        language: browserLanguage,
        positionMode: true,
        theme: {
          name: 'dracula',
          detail: { primary: '#0f5fd3' },
          cardColor: '#ff79c6',
          cardWidth: 140,
          cardHeight: 200,
          textColor: '#ffffff',
          luckyCardColor: '#ECB1AC',
          textSize: 30,
          patternColor: '#1b66c9',
          patternList: defaultPatternList,
          background: {},
        },
        musicList: defaultMusicList,
        imageList: defaultImageList,
      }
      this.currentMusic = { item: defaultMusicList[0], paused: true }
    },
  },
  persist: {
    enabled: true,
    strategies: [
      { storage: localStorage, key: 'globalConfig', paths: ['globalConfig'] },
    ],
  },
})
